/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_devtcg_demo_jnitest_NativeMD5 */

#ifndef _Included_org_devtcg_demo_jnitest_NativeMD5
#define _Included_org_devtcg_demo_jnitest_NativeMD5
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_devtcg_demo_jnitest_NativeMD5
 * Method:    digestStream
 * Signature: (Ljava/io/InputStream;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_devtcg_demo_jnitest_NativeMD5_digestStream
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_devtcg_demo_jnitest_NativeMD5
 * Method:    digestFile
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_devtcg_demo_jnitest_NativeMD5_digestFile
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
